# Generated by Django 6.0.1 on 2026-01-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pizzas/')),
            ],
        ),
    ]
