# Generated by Django 6.0.1 on 2026-01-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizzas',
            new_name='Pizza',
        ),
    ]
